### ISSUE TITLE
Make the box scrollable

### ISSUE THREAD

**Issue by yassine04e** [TravelPouch/travelpouch#117]

**Comment by RemIsMyWaifuu** [comment]
As discussed during various meetings

Description:
The idea is to make the reminder banner bigger, in the middle of the screen and have a scrollable list of all upcoming activities in a nicer way.

Acceptance Criteria:

- Remind Banner UI:

1. Centered view, taking up 30% of the screen height, constrained on the sides
2. Scrollable column displaying all activities due in less than 24 hours.
3. Individual entries are displayed with an dash in front of them

- Remind Banner Model:
1. Activities that are to be displayed should be sorted in increasing order of due time.
