### ISSUE TITLE
Sign-in Persistance

### ISSUE THREAD

**Issue by RemIsMyWaifuu** [TravelPouch/travelpouch#190]
Description: Currently, if a user gets back to the sign-in page even though they have already authenticated they must reauthenticate again. This also holds for after the application has been shutdown.
Acceptance Criteria:
- User doesn't need to be reauthenticated if he returns to the sign-in screen again during an active user flow
- User doesn't need to be reauthenticated after leaving the application if it has already authenticated before hand

**Comment by loggerz** [comment]
**NB: this issue is important as it is a blocker for #185 to be used in practice (but independent implementation-wise)**
