### ISSUE TITLE
fix : uid validity check is not correct

### ISSUE THREAD

**Issue by Unsaved2** [TravelPouch/travelpouch#23]
https://github.com/TravelPouch/travelpouch/blob/c3945684052bd0a007093d4f3e2b0690d5590d61/app/src/main/java/com/github/se/travelpouch/model/TravelContainer.kt#L70

Hi, you forgot to add ^ to ensure that the strings begin with the correct capture group and you forgot the $ at the end. This ensure that only string that exactly 20 characters matches, corresponding to this format :  https://github.com/firebase/firebase-android-sdk/blob/a024da69daa0a5264b133d9550d1cf068ec2b3ee/firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java#L35

**Comment by RemIsMyWaifuu** [comment]
Alright, thank you for bringing this to my attention. I'm on it, that's an oversight on my part. I will also add a regression test so that this behaviour is ironclad. 😅
