### ISSUE TITLE
[US6] View for listing documents

### ISSUE THREAD

**Issue by ArthurChalard** [TravelPouch/travelpouch#41]
Add a view with the list of documents uploaded (either via email import, scan or local file). As this view is the first interaction with the database we define the current model for Documents : 

- documentId
- travelId
- activityId (optional, travel global if not specified)
- title (user-defined or derived from original filename)
- fileFormat (mime type, one of `image/jpeg`,`image/png`,`application/pdf`)
- fileSize (in bytes, useful for offline storage later on)
- addedByEmail (null or email of origin)
- addedByUser (null or user who uploaded)
- addedAt (timestamp)
- thumbnails (for later user, an object (map) with status of each thumbnail size)
- visibility (for later use, either: ME, ORGANIZERS, PARTICIPANTS)

**Comment by loggerz** [comment]
(Updated the data model)
Also for the reference pattern for Cloud Storage we plan to use `documents/<travel-id>/<document-id>-<file-type>` with file type as either `original` or `thumb` to distinguish the variants of the same document.
More info from Google Cloud Storage docs [here](https://firebase.google.com/docs/storage/android/create-reference?hl=en&authuser=0)
