### ISSUE TITLE
Implement the basic UI of Notifications

### ISSUE THREAD

**Issue by yassine04e** [TravelPouch/travelpouch#92]
Implement a UI where the user be notify about events in the application. These events were implemented in #93 and include invitation to travels and role change notification. The UI must contains sections depended on the time of the notification (This week, Last week, Last month, Last Year). The invitation notifications must contains red button to decline the invitation and a green button to accept the invitation.

**Comment by appellet** [comment]
Here's an idea of what the message view should look like in the next Sprint #92 

![image](https://github.com/user-attachments/assets/79f22768-2ccc-4a7b-971d-fad2d959c116)


https://excalidraw.com/#room=90d9447e3b4a15584712,ZoOhkmuNak8utVn2a-gwuw
