### ISSUE TITLE
Implement the logic to manage the notifications

### ISSUE THREAD

**Issue by yassine04e** [TravelPouch/travelpouch#93]
Implement the logic to manage the suggestions. So modelView and repository. So if a user1 wants to add another user2, a notification is sent to user2 (and he can accept or decline) and the choice of user2  is sent back to user1

**Comment by appellet** [comment]
Here's an idea of what the message view should look like in the next Sprint #92 

![image](https://github.com/user-attachments/assets/79f22768-2ccc-4a7b-971d-fad2d959c116)


https://excalidraw.com/#room=90d9447e3b4a15584712,ZoOhkmuNak8utVn2a-gwuw
